services:
  mcp-server:
    container_name: mcp-server
    build:
      context: ./mcp-server
    ports:
      - "9090:9090"
    env_file:
      - ./mcp-server/.env
    networks:
      - agent-network
    volumes:
      - ./videos:/app/videos
  agent-api:
    container_name: agent-api
    build:
      context: ./agent-api
    ports:
      - "8080:8080"
    environment:
      - DISABLE_NEST_ASYNCIO=True
    env_file:
      - ./agent-api/.env
    networks:
      - agent-network
    depends_on:
      - mcp-server
    volumes:
      - ./videos:/app/videos
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - agent-api
      - mcp-server
    networks:
      - agent-network
    volumes:
      - ./videos:/app/videos

networks:
  agent-network:
    name: agent-network

volumes:
  videos: