services:
  mcp-server:
    container_name: mcp-server
    build:
      context: ./mcp-server
    ports:
      - "8000:8000"
    env_file:
      - ./mcp-server/.env
    networks:
      - agent-network
  agent-api:
    container_name: agent-api
    build:
      context: ./agent-api
    ports:
      - "8080:8080"
    env_file:
      - ./agent-api/.env
    networks:
      - agent-network
    depends_on:
      - mcp-server
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - agent-api
      - mcp-server
    networks:
      - agent-network

networks:
  agent-network:
    name: agent-network